export interface TravelerDetailsform {
    salutation:string,
    firstName:string,
    middleName:string,
    surName:string,
    gender:string,
    dateOfBirth:string,
    passportNo:string,
    emailId:string,
    phoneNumber:string,
    alternatePhoneNumber:string,
    addressLine_1:string,
    addressLine_2:string,
    addressLine_3:string,
}
